### PR TITLE
chore: unpin peerDependencies

### LINKED ISSUE #670: Don't pin peerDependencies
AFAIK `peerDependencies` should not be pinned.

**Why?**

I get warnings for `peerDependencies` (My versions are compatible [semver] but later releases). While it's fully ok to pin `dependecies` and `devDependencies` to ensure a stable build and release, `peerDependecies` should not force exact versions.

```bash
warning "workspace-aggregator-8ff153bc-bc61-4fd3-b3af-d3d822314b14 > website > react-mapbox-gl@4.0.2" has incorrect peer dependency "mapbox-gl@0.51.0".
warning "workspace-aggregator-8ff153bc-bc61-4fd3-b3af-d3d822314b14 > website > react-mapbox-gl@4.0.2" has unmet peer dependency "prop-types@15.6.2".
warning "workspace-aggregator-8ff153bc-bc61-4fd3-b3af-d3d822314b14 > website > react-mapbox-gl@4.0.2" has incorrect peer dependency "react@16.5.2".
warning "workspace-aggregator-8ff153bc-bc61-4fd3-b3af-d3d822314b14 > website > react-mapbox-gl@4.0.2" has incorrect peer dependency "react-dom@16.5.2".
```

**Suggested changes:**

https://github.com/alex3165/react-mapbox-gl/blob/master/package.json#L70-L75

**Before:**

```json
{
  "peerDependencies": {
    "mapbox-gl": "0.51.0",
    "prop-types": "15.6.2",
    "react": "16.5.2",
    "react-dom": "16.5.2"
  }
}
```

**After:**

```json
{
  "peerDependencies": {
    "mapbox-gl": "^0.51.0",
    "prop-types": "^15.6.2",
    "react": "^16.5.2",
    "react-dom": "^16.5.2"
  }
}
```

### PR DESCRIPTION
**Pull request by pixelass**
closes #670

### CODE REVIEW

**Comment by lehresman** [comment]
Any chance this can get merged?  Our project has other dependencies that make using react-mapbox-gl impossible with its pinned peer dependencies.

**Comment by Wykks** [comment]
While I find it ok for react deps to be flexible with ^ ; I don't think it's a good idea to unpin mapbox-gl dep.
mapbox-gl is not following semantic versioning, so any mapbox-gl update can introduce breaking change. Thus any mapbox-gl update can potentially break react-mapbox-gl.

But at the end of the day, it's just a hint, it should'n block anything (except if you want 0 warning when installing deps...)

**Comment by johnisutanto** [comment]
I would like to check if we could modify this PR to have the react dependency to ^16.5.2 and have this merge soon. I am facing the same issue with my project where I need to specifically work with react 16.5.2 since this library need this specific version. I can't upgrade to latest react 16.

**Comment by johnisutanto** [comment]
@pixelass - I don't have write access, can you help to merge? Also, I don't know what the process for creating new release for this library after the merge.

**Comment by pixelass** [comment]
@johnisutanto 	I am not a member of this project. Maybe @Wykks can help

**Comment by radeno** [comment]
Any chance to check and approve PR ? @alex3165 @Wykks

**Comment by mklopets** [comment]
Sorry for the massive delay. It looks to me like mapbox-gl does actually use semver. It's just pre-1.0.0 and so, as per the semver spec, the minor and patch numbers don't have to mean anything.

But, looking at recent releases, seems to me that they're following the convention where they bump the minor version for breaking changes. This means that using the caret gives us the intended functionality (matching versions within the same minor only when pre-1.0.0).

**Comment by Wykks** [comment]
Indeed, I didn't know about the special pre-1.0.0 thing :+1:

**Pull request closed without merging**
