### PR TITLE
React.createContext & typescript 2.9.1

### LINKED ISSUE #520: Upgrade to Typescript 2.7

### PR DESCRIPTION
**Pull request by brendanmoore**
This PR updates the map context to use the new `React.createContext` pattern. This has also had the bonus of removing `prop-types` as a dependency. In addition typescript is upgraded to 2.9.1. (closes #520, #578)

A cool thing we could do is expose `MapConsumer` so users could have direct access to the map instance in context without having to rely on an `onStyleLoaded` side-effect.

### CODE REVIEW

**Comment by brendanmoore** [comment]
So it seems that the fixes in #502 has created an issue with the cluster markers no longer being rendered as a child of the expected `parentElement` div use in `Cluster.zoomToClusterBounds`. If we want to keep the API the same i.e. having access to the `parentElement` for `<Cluster style={...} className={...} />` the `ProjectLayer` API will probably need to be refactored to handle optional containers for the `ReactDOM.createPortal`

**Comment by brendanmoore** [comment]
5e8205a Has resolved the `Cluster.zoomToClusterBounds` issue by hoisting the `createPortal` implementation in #502 to `map.tsx`

**Comment by brendanmoore** [comment]
@mklopets I rebased masters updates into my `v4` fork branch mainly to get the updates to GeoJSON and the latest mapbox-gl version, it has obviously left things a bit messy. It might make sense for the someone with write access to merge master into `v4` to clean it up a bit? What do you think?

**Comment by mklopets** [comment]
Sure, I'll rebase the v4 branch on top of master. Thanks for your work btw, @brendanmoore!

**Comment by brendanmoore** [comment]
I am going to clean up the commits close this PR and resubmit.

**Comment by brendanmoore** [comment]
Replaced by #619

**Pull request closed without merging**
