### PR TITLE
fix: Type mismatch in module augmentation for mapbox-gl

### LINKED ISSUE #666: Type RequestTransformFunction should be RequestTransformFunction
While building my project, I noticed that the RequestTransformFunction type is incorrectly named versus @types/mapbox-gl. See https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c6f73c8050c16ceb3a9ac23df466361e9e22a4a1/types/mapbox-gl/index.d.ts

The error message when I compile with TypeScript: 

```
/node_modules/react-mapbox-gl/lib/map.d.ts
(82,13): Subsequent property declarations must have the same type.  Property 'transformRequest' must be of type 'TransformRequestFunction | undefined', but here has type 'RequestTransformFunction | undefined'.
```

### PR DESCRIPTION
**Pull request by pducks32**
Fixes #666 

I was running into this issues and was just overwriting the definition myself. I felt bad because others saw the same problem so I thought I'd try to be helpful and fix it. This library is great and I respect it a ton but I am new to contributing to it so if I can do anything to fix this issue in a better, or more sustainable way I'd be happy to help. Thanks.

### CODE REVIEW

**Comment by pducks32** [comment]
Moreover I'm curious as to why the module augmentation is there? Is it because the type definition of that is new or do you require the `any` return for some reason? I couldn't find a use that would require the definition but maybe you want to keep the outer API simple and not require a consumer to import complicated `mapbox-gl` types.

**Comment by danvk** [comment]
FYI I confirmed that this PR fixes the type error in my client. Would be great to get a release with this fix!

**Comment by klaseskilson** [comment]
I'm experiencing this too. (FWIW, Tried to reproduce it using the [debug repo](https://github.com/alex3165/react-mapbox-gl-debug), but that is outdated in react-scripts, react, mapbox-gl and react-mapbox-gl.)

**Comment by chenasraf** [comment]
So, is this ever going to be merged in?

**Comment by pducks32** [comment]
@alex3165 What can I do to help get this merged?

**Comment by rob137** [comment]
Has there been any news on this since Feb?  Would love to see this merged.

**Comment by danvk** [comment]
pinging a few others with commit rights on this repo: @mklopets @daniel-hauser 

This is a one liner that will let users update to something more recent than TypeScript 3.1.

**Comment by mklopets** [comment]
@danvk thanks for the direct ping. Will get this released today.

**Comment by mklopets** [comment]
Released as `v4.2.4`. Sorry for the delay. The maintainers have sadly been quite busy this beginning of the year. Maintenance and development should pick up speed once again now, though.

**Comment by mklopets** [comment]
& thanks everyone for helping (each other) on the issue and in the PR!

**Comment by mklopets** [comment]
@danvk pains me to admit it but my own projects' TS version was also stuck behind this for a long time

**Pull request merged**
