### PR TITLE
React 16

### PR DESCRIPTION
**Pull request by jthetzel**
For consideration for #381.

Upgrading to React 16 was mostly straight forward. Complexity arose with `enzyme@3.0.0`, which requires `enzyme-adapter-react-16`. Configuration of enzyme 3 is moved to `src/jest/setupTestFrameworkScriptFile.ts` . A work around for a React 16 requestAnimationFrame jest error is in `src/jest/setupFile.ts` (further discussion: https://stackoverflow.com/a/43950142/583830 ). Both files are referenced in the jest section of `package.json`. They needed to be in separate files, otherwise the requestAnimationFrame work around would fail.

Type definitions are not yet available for `enzyme@3.0.0` or `enzyme-adapter-react-16`, to my knowledge. The `src/jest` directory is ignored in `tsconfig.json`.

This PR passes local tests and runs in the react-mapbox-gl-debug repository.

### CODE REVIEW

**Comment by alex3165** [comment]
Good job! thank you for the PR, could you update `react` and `react-dom` in the example too?

**Comment by jthetzel** [comment]
Example upgraded to react, react-dom @16.0.0. In the example, console reports three warnings for `onKeyDown`, `onKeyUp`, and `onClick`:
`Warning: Expected `onKeyDown` listener to be a function, instead got a value of `boolean` type.`

These appear to be due to DOM attribute changes in React 16 (see https://github.com/alexkuz/react-json-tree/issues/94 ). The warnings likely stem from three lines in the react-live Editor ( https://github.com/FormidableLabs/react-live/blob/ed390f5ea5a084c3e2d447147d619ec0c9d10108/src/components/Editor/index.js#L210 ). Changing, for example, `onKeyDown={contentEditable && this.onKeyDown}` to `onKeyDown={contentEditable? this.onKeyDown : undefined}` should resolve the warnings.

**Comment by alex3165** [comment]
@jthetzel I think @philpl released the new version of react-live, you can go ahead with the update. Although can you please update the types accordingly? 👍 Sorry it is a lot of overhead but I want to keep everything in sync

**Comment by jthetzel** [comment]
`@types/react` and `@types/react-dom` upgraded to latest versions in root and example. `@types/react-dom` is still at v15, awaiting https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20065 . `react-live` is still @1.7.1 on npm, so no upgrade yet.

**Comment by jthetzel** [comment]
`@types/react-dom` now @16.0.0. Just awaiting the next `react-live` release.

**Comment by alex3165** [comment]
@jthetzel I think we can go out with this, the react-live issue is just a warning happening in the examples, could you rebase from master? and we are good

**Comment by jthetzel** [comment]
I'll squash these together and reply back in a few hours when done.

**Comment by jthetzel** [comment]
All done.

**Pull request merged**
