### PR TITLE
Start Feature.onDragStart implementation

### PR DESCRIPTION
**Pull request by cyrilchapon**
Following on https://github.com/alex3165/react-mapbox-gl/issues/412

### CODE REVIEW

**Comment by cyrilchapon** [comment]
This is a first implementation, to validate strategy.

It need reviews, and help.

Also, I couldn't find some tests about features, so I didn't implemented one (it would need whole bootstrapping and it's way over my knowledge).

I couldn't test it by hand, since I don't get anything to Typescript. Tried to `npm run prepublishOnly` and `npm link` it inside my project, but got errors.

**Comment by alex3165** [comment]
Hey @cyrilchapon thanks for helping on this, what do you think about something like this? https://github.com/alex3165/react-mapbox-gl/pull/519/files

**Comment by cyrilchapon** [comment]
I reworked the entire file, cleaned up and implemented `onDrag` and `onDragEnd`. Gonna make another PR

**Comment by cyrilchapon** [comment]
(Because the actual implementation also suffered from a bug : when clicking on a feature (anywhere not at the center), it would trigger a `onDragEnd` (+others) event)

**Pull request closed without merging**
