### PR TITLE
remove injectCss

### PR DESCRIPTION
**Pull request by nathanredblur**
Remove injectCss in favor of include manually the css in the way that the user needs.

### CODE REVIEW

**Comment by suprMax** [comment]
@alex3165 any chance of getting this in?

**Comment by jordymeow** [comment]
Please, can you really get this into the next release? We have to use tricks to avoid that css in NextJS, Electron, etc...

**Comment by JClackett** [comment]
Pleaseee merge

**Review by RadovanPelka — APPROVED** [review]

**Comment by alex3165** [comment]
Sorry for the delay, merging this

**Comment by alex3165** [comment]
Released as part of react-mapbox-gl 5.0.0, please refer to [Mapbox CSS guideline](https://docs.mapbox.com/mapbox-gl-js/api/#mapbox-css) to include the CSS from now on

**Pull request merged**
