### PR TITLE
Refactor feature drag events 

### PR DESCRIPTION
**Pull request by alex3165**

### CODE REVIEW

**Comment by alex3165** [comment]
Oh yes I see what you mean, is it an issue for you or can we address this issue separately?

**Comment by cyrilchapon** [comment]
Well, our PR doesn't degrade anything and improve the stuff. I think we can merge this, and reopen for multi drag bug

(Also I personally need that PR so badly 😅)

With that PR merged it makes a good foundation for fixing the rest, I'll have a chance to work on it next weeks

**Comment by alex3165** [comment]
@cyrilchapon I found some time to improve the logic around the dragging, I think all the use cases are now addressed, if you want to spend some time testing it in your application that would be perfect.

Sorry for the diff, I ran prettier and re-generated the raw files.

**Comment by cyrilchapon** [comment]
Hey. Sorry for the delay.

I might have a chance to test it soon, but I've got a challenging sprint to end before :)

Will it be published to npm ?

**Comment by alex3165** [comment]
@cyrilchapon I published it, you should get all those updates in version `3.8.0`

**Comment by cyrilchapon** [comment]
I installed it and tested.

It turns out :

### Desktop

#### positive :
- onDrag / onDragStart / onDragEnd work correctly
- onClick is fixed and behave normally with onDrag (previously, clicking on an offseted feature lead to a drag and not a click)

#### negative :
- This introduced a light bug : when dragging too fast, the Feature disappear and reappear with a fade animation. I digged into it but just couldn't find why oO

#### improvements :
- possible improvement, add a 'dragTriggerPadding' option, that would make an onclick under it and drag over it. To make it "snap" until really dragged

**Comment by cyrilchapon** [comment]
@alex3165 

There seem to be an issue with the mice on the dragged marker when you drag too fast.
Also the marker disapear when dragging

**Pull request merged**
