### PR TITLE
Add maxDecimalPlaces to Marker component

### PR DESCRIPTION
**Pull request by VilliGunn**
There is a blur issue with Chrome and Safari when the translate property has a pixel value with decimal numbers.

I added a prop for the Marker component that controls how many, if any decimal places should be used. Not sure the control option is needed, maybe the maxDecimalPlaces should just be set to `0` by default.

Here I am not using maxDecimalPlaces:
blur

Here I am using maxDecimalPlaces:
noblur

You will need to click on the images to get the full res image.

Both images from Chrome 55.0.2883.95

Please feel free to make changes or comments on this :)

### CODE REVIEW

**Comment by alex3165** [comment]
Thanks for the PR, is there a considerable position shift if you max zoom to a `Marker` and check with `toFixed(0)` and without ?

**Comment by VilliGunn** [comment]
Here you can see a `Marker` with and without decimal numbers on max zoom

With decimal:
decimal

Without decimal:
nodecimal

I can't see any considerable position shift for this specific `Marker` at least. If there are no decimals the `Marker` can only move max 0.5 pixels on both the X and Y axis.

**Comment by alex3165** [comment]
Ok, then I guess when can go with a `toFixed(0)` by default 👍  would you mind doing the change ?

**Comment by alex3165** [comment]
Awesome thank you 👍

**Pull request merged**
