### PR TITLE
Upgrade mapbox-gl to 0.43.0

### PR DESCRIPTION
**Pull request by jthetzel**
Upgrade mapbox-gl to 0.43.0.

Also set react, react-dom peerDependencies to 16.0.0, loosen peerDependencies, and upgrade recompose to @0.26.0.

### CODE REVIEW

**Comment by alex3165** [comment]
Hey @jthetzel Thanks for the PR 👍

**Comment by jthetzel** [comment]
Before this can be merged, we need to address https://github.com/mapbox/mapbox-gl-js/pull/5562 , which introduces a breaking change causing an error to be thrown if a source is removed while still in use (e.g. remove a source prior to removing layers that use the source).

Example error:
```
Error: Source "waterTemperatureSourceId" cannot be removed while layer "waterTemperatureLayerId" is using it.
    at t.removeSource (bundle.js:172184)
    at e.removeSource (bundle.js:172298)
    at Source../node_modules/react-mapbox-gl/lib/source.js.Source.componentWillUnmount (bundle.js:169161)
    at callComponentWillUnmountWithTimer (bundle.js:147670)
    at HTMLUnknownElement.callCallback (bundle.js:139480)
    at Object.invokeGuardedCallbackDev (bundle.js:139519)
    at invokeGuardedCallback (bundle.js:139376)
    at safelyCallComponentWillUnmount (bundle.js:147677)
    at commitUnmount (bundle.js:147803)
    at commitNestedUnmounts (bundle.js:147839)
    at unmountHostComponents (bundle.js:148122)
    at commitDeletion (bundle.js:148172)
    at commitAllHostEffects (bundle.js:148864)
    at HTMLUnknownElement.callCallback (bundle.js:139480)
    at Object.invokeGuardedCallbackDev (bundle.js:139519)
    at invokeGuardedCallback (bundle.js:139376)
    at commitRoot (bundle.js:148953)
    at performWorkOnRoot (bundle.js:149955)
    at performWork (bundle.js:149905)
    at batchedUpdates (bundle.js:150024)
    at batchedUpdates (bundle.js:141268)
    at dispatchEvent (bundle.js:142359)
```

**Comment by alex3165** [comment]
Thank you, can you open the PR again? I reverted it

**Comment by jthetzel** [comment]
I'll reproduce in an example demo and open a new issue.

**Pull request merged**
