### PR TITLE
update Layer minZoom and maxZoom on changes

### PR DESCRIPTION
**Pull request by redbmk**
minZoom and maxZoom do not update on changes.

**Warning**: this is not building properly right now, and I get a linting error with tsserver, but I can't figure out what's wrong. I didn't want to create both an issue and a pull request, so I thought we could iterate on this.

The error I get with `npm run build` is
```
src/layer.ts(265,33): error TS2345: Argument of type 'number | undefined' is not assignable to parameter of type 'number'.
  Type 'undefined' is not assignable to type 'number'.

```

From what I can tell these are optional params in both `mapbox-gl` and `react-mapbox-gl`, so I'm not sure how to fix the error

### From `react-mapbox-gl/src/layer.ts` (typescript)
```
  minZoom?: number;
  maxZoom?: number;
```

### From `mapbox-gl/src/style/style.js` (flow)
```
  setLayerZoomRange(layerId: string, minzoom: ?number, maxzoom: ?number) {
```

### CODE REVIEW

**Comment by alex3165** [comment]
Hey @redbmk sorry for the late reply, so that's an issue with the type definition of mapbox-gl in definitelyTyped, for now you can do:
```ts
map.setLayerZoomRange(id, props.minZoom!, props.maxZoom!);
```

Can you also add a Todo like:
```
// TODO: Fix type definition of mapbox-gl for setLayerZoomRange optional zooms
map.setLayerZoomRange(id, props.minZoom!, props.maxZoom!);
```

**Comment by redbmk** [comment]
@alex3165 Thanks. I ended up creating a PR to fix DefinitelyTyped (DefinitelyTyped/DefinitelyTyped#22036). I also found the tests weren't passing there, but I'm not entirley sure the best way to fix it so I submitted an issue (DefinitelyTyped/DefinitelyTyped#22035).

Do you have a preference whether to wait for these to get updated first or to just add the `!`s for now?

I've already coded a workaround for now in my code by just calling `this.context.map.setLayerZoomRange` in `componentWillReceiveProps`

**Comment by alex3165** [comment]
I think we can go ahead with the bang operator (`!`) for now and add a comment:
```
Todo: Fix when PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22036 is merged
```

**Comment by redbmk** [comment]
@alex3165 Sounds good, thanks :smile:

**Comment by alex3165** [comment]
@redbmk Is it good on your side? can we get this merged?

**Comment by redbmk** [comment]
@alex3165 yeah, we're good to go. I tested this out and it's working great for me.

**Comment by alex3165** [comment]
Released with tag `3.4.0`

**Pull request merged**
