### PR TITLE
Examples with custom tiles

### PR DESCRIPTION
**Pull request by stereobooster**
Examples with custom tiles. Probably need to clean up it a bit. What do you think?

### CODE REVIEW

**Comment by stereobooster** [comment]
tried react-snapshot, but it has this issue https://github.com/geelen/react-snapshot/issues/16

**Comment by stereobooster** [comment]
Added Marker, Popup example

**Comment by alex3165** [comment]
@stereobooster Thanks for the PR, Great job but I am not sure about the value of having examples with custom tiles. In the end what changed for the library is just the style passed down to the map, it doesn't show more features that `react-mapbox-gl` provide.

What I can propose you is to keep this into a different repository and I will add a link to it in the readme as "More examples using react-mapbox-gl", what do you think about it ?

**Comment by stereobooster** [comment]
My intention was to show that library actually not coupled with Mapbox tile server on one side, on other side this is not well documented feature. 

I like how examples organised in [styleguidist](http://react-styleguidist.js.org/) or in [https://uber.github.io/react-map-gl/#/](react-map-gl): Code example + Demo.

From my POV the more examples the better. WDYT?

**Comment by alex3165** [comment]
I agree with you for the organisation of the examples (code + example), let me have a look at the actual result of the examples on your PR (will check this week).

**Comment by stereobooster** [comment]
Just a note this is not deployable without some kind of static prerenderer, like react-snapshot, because I use react-router.

**Comment by alex3165** [comment]
Sorry I will close this PR as the examples changed completely with the version 2.0.0

**Pull request closed without merging**
